[package]
name = "tesql-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tesql = { path = "../tesql", version = "0.1.0" }
structopt = { version = "0.3", default-features = false }
